### ISSUE TITLE
Import errors in test script indoor_ds_rgbd.sh

### ISSUE THREAD

**Issue by barbararoessle** [Ryan-prime/3DG-STFM#1]
Hi! 

Thanks a lot for providing the code! 
Which of the 2 test scripts do I need to run to reproduce the results in Tab. 1 (ScanNet) of your paper?
When I run `bash ./scripts/test/indoor_ds.sh`, I get the following results, which are a bit lower than in the paper:
```
{'auc@10': 0.43240685010098917,
 'auc@20': 0.6057994724434057,
 'auc@5': 0.23673030840943987,
 'prec@5e-04': 0.8468239684575063}
```
When I run the other test script, `bash ./scripts/test/indoor_ds_rgbd.sh`, I get 2 import errors for `MultiSceneDataModule` and `PL_LoFTR`. It looks like there is no implementation for them, but they also do not seem to be used, so i removed the imports. 
Then, I run into a problem with loading the state dict:
```
Traceback (most recent call last):
  File "./test_rgbd.py", line 57, in <module>
    model = PL_LoFTR_RGBD(config, pretrained_ckpt=args.ckpt_path, profiler=profiler, dump_dir=args.dump_dir)
  File "/mnt/login_home/3DG-STFM/src/lightning/lightning_loftr.py", line 341, in __init__
    self.matcher.load_state_dict(new_state_dict, strict=False)
RuntimeError: Error(s) in loading state_dict for LoFTR_RGBD:
        size mismatch for backbone.conv1.weight: copying a param with shape torch.Size([128, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([128, 4, 7, 7]).
```
I would much appreciate, if you could take a look at this, maybe I am missing something. Thanks in advance!

**Comment by Ryan-prime** [comment]
Thank you for the question! For the first one, it seems ```auc@5``` is slightly higher but other two ```auc@20``` and ```auc@10``` are a little bit lower if we compare with the paper results. We currently need to check the model to see whether we upload the wrong checkpoint. Sorry about that. For the second one: ```indoor_ds_rgbd.sh``` is used to test teacher model, which need RGBD image as input (4-channel). The ckpt path is not correct since we have not release that model yet.

**Comment by barbararoessle** [comment]
Thanks!
